## Author: Alper Sarikaya
## Last modified: 2020-07-28
## This script should be run on every commit to an active branch on this repository.
## This action will build the entire site from scratch and deploy to the staging S3 bucket.

name: build and deploy

on:
  push:
    # build and deploy whenever someone pushes to master
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    ## SET UP STEPS
    - name: Checkout this commit
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-deploy.txt
    - name: Set up AWS credentials (+ set default user)
      run: |
        mkdir -p ~/.aws
        touch ~/.aws/credentials
        echo "[default]
        aws_access_key_id =  ${{ secrets.aws_deploy_key_id }}
        aws_secret_access_key =  ${{ secrets.aws_secret_access_key }}" > ~/.aws/credentials
      ## SET IEEEVIS_AWS_USER environment variable to "default" in deploy step
       
    ## BUILD AND DEPLOY!
    - name: Build and deploy
      env:
        IEEEVIS_AWS_USER: default
      run: |
        make build-deploy
      
    
